<a href="https://colab.research.google.com/github/FelixBuk/tod-Colab/blob/main/%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B8_1_%D1%81%D0%B5%D0%BC%D0%B8%D0%BD%D0%B0%D1%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Сгенерировать двухмерный массив arr размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  ax+b  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0


In [ ]:
import numpy as np #
a1 = np.random.normal(0, 20, (4, 7))
print(np.random.uniform(0, 20, (4, 7)))

[[13.79192273 14.32676666  9.56383297  3.31024679 12.58244785  8.08769627
   7.72881111]
 [ 8.83926006 14.12530614  6.99401099 17.42738382  3.52583362  5.35312881
   3.51059289]
 [ 2.27746385 14.93375761 10.93914217 16.41453491  8.88736452  0.99283058
   7.87815404]
 [ 2.21191909  2.10768116 15.82056117  2.26755862  2.54953673  6.20825139
   1.5516657 ]]



Создать матрицу 8 на 10 из случайных целых (используя модуль numpy.random) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
a2 = np.random.randint(0, 20, (8, 10))
print(a2)
s = np.sum(a2, axis = 1)
ind = np.argmin(s)
print(ind)
print(a2[ind])

[[ 8 18  6 15  7 12  5  0  1  4]
 [ 7 11  4 18 19 11  0 16 10  5]
 [13  5  3 10 12 12  4  6 17 18]
 [16  5 13 18  7  9 11  3  6 18]
 [ 9  2  0 19 11 10  8 13  3  1]
 [15 11  8 18  1 12 14 10 17  2]
 [13  0 15 14 17  7 12  0 14  8]
 [ 5  4 17  1 11  1  1 13  7  0]]
7
[ 5  4 17  1 11  1  1 13  7  0]


Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
from scipy.spatial import distance
a = [1, 2, 3]
b = [4, 5, 6]
print(distance.euclidean(a, b))

5.196152422706632


Решить матричное уравнение A*X*B=-C - найти матрицу X. Где A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]], B=[[3, -1], [2, 1]], C=[[7, 21], [11, 8], [8, 4]].

In [ ]:
import numpy as np
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b=np.array([[3, -1], [2, 1]])
c=np.array([[7, 21], [11, 8], [8, 4]])
x1 = [[1, 1, 1], [1, 1, 1]]
a1 = np.linalg.inv(a).dot(-c)
a2 = a1.dot(np.linalg.inv(b))
print(a2)

[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]
